=== hromei/proiect1/conținut/persoane.dtd
<!ELEMENT persoane (persoane,persoana, nume, prenume,varsta,telefon,adresa,strada, numar,localitate,oras,judet,tara,educatie,data,titlu,organisation-providing-education)>
<!ELEMENT persoana (#PCDATA)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT educatie (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT titlu (#PCDATA)>
<!ELEMENT organisation-providing-education (#PCDATA)>

=== hromei/proiect1/conținut/persoane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
	<persoana id="1">
		<nume>
			Popescu
		</nume>
		<prenume>
			Ion
		</prenume>
		<varsta>
			23
		</varsta>
		<telefon>
			0745123456
		</telefon>
		<adresa>
			<strada>
				Nucilor
			</strada>
			<numar>
				15
			</numar>
			<localitate>
				Iasi
			</localitate>
			<judet>
				Iasi
			</judet>
			<tara>
				Romania
			</tara>
		</adresa>
		<educatie>
			<data>
				01.10.2017-01.07.2021
			</data>
			<titlu>
				Student
			</titlu>
			<organisation-providing-education>
				TU IASI
			</organisation-providing-education>
		</educatie>
	</persoana>
	<persoana id="2">
		<nume>
			Hromei
		</nume>
		<prenume>
			Andreea
		</prenume>
		<varsta>
			22
		</varsta>
		<telefon>
			0742753856
		</telefon>
		<adresa>
			<strada>
				bld. Tudor Vladimirescu
			</strada>
			<numar>
				0000
			</numar>
			<localitate>
				Iasi
			</localitate>
			<judet>
				Iasi
			</judet>
			<tara>
				Romania
			</tara>
		</adresa>
		<educatie>
			<data>
				01.10.2017-01.07.2021
			</data>
			<titlu>
				Student
			</titlu>
			<organisation-providing-education>
				TU IASI
			</organisation-providing-education>
		</educatie>
	</persoana>
	<persoana id="3">
		<nume>
			Duduman
		</nume>
		<prenume>
			Bianca
		</prenume>
		<varsta>
			21
		</varsta>
		<telefon>
			0745157651
		</telefon>
		<adresa>
			<strada>
				Ciric
			</strada>
			<numar>
				123
			</numar>
			<localitate>
				Iasi
			</localitate>
			<judet>
				Iasi
			</judet>
			<tara>
				Romania
			</tara>
		</adresa>
		<educatie>
			<data>
				01.10.2017-01.07.2021
			</data>
			<titlu>
				Student
			</titlu>
			<organisation-providing-education>
				TU IASI
			</organisation-providing-education>
		</educatie>
	</persoana>
</persoane>
